Metrics/LineLength:
  Max: 200

AllCops:
  Exclude:
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'test/test_helper.rb'
    - 'db/migrate/*'
    - 'app/helpers/admin/*'
    - 'app/models/game.rb'
    - 'test/models/game_test.rb'
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'spec/teaspoon_env.rb'
Rails:
  Enabled: true

Documentation:
  Enabled: false

MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

# to remove restriction on complexity
Metrics/CyclomaticComplexity:
  Enabled: false

# to remove restriction on complexity
Metrics/PerceivedComplexity:
  Enabled: false

# to remove restriction on nesting
Metrics/BlockNesting:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Style/GuardClause:
  Enabled: false