language: ruby

rvm:
  - 2.1.6
  - 2.1.7

env:
  - DB=sqlite3

before_script:
  - bundle exec rake db:schema:load RAILS_ENV=test
  - bundle exec rake db:test:prepare RAILS_ENV=test
  - bundle exec rake db:fixtures:load RAILS_ENV=test

script:
  - bundle exec rake test test:models
  - bundle exec rspec spec/